model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    beta_schedule: cosine
    var_parameterization: learned_range
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: multimodal_sr
    image_size: 256
    channels: 3
    concat_mode: true
    cond_stage_trainable: false
    unet_config:
      target: ldm.modules.diffusionmodules.imagenmodel.EfficientUNetModel
      params:
        in_channels: 6
        out_channels: 6
        model_channels: 128
        attention_resolutions: [32, 16]
        num_res_blocks: [2, 2, 4, 6]
        channel_mult: [1, 2, 4, 8]
        num_heads: 8
        num_head_channels: 64
        resblock_updown: true
        use_scale_shift_norm: true
        use_spatial_transformer: false
        checkpoint: fairscale
        skip_rescale: true
        context_dim: 768
        contexts:
          vision:
            seq_dim: 1024
            pooled_dim: 1024
          lang:
            seq_dim: 2048
            pooled_dim: 2048
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenPretrainedSuperResEmbedder
      params:
        vision_model_name: google/vit-large-patch16-224
        lang_model_name: google/t5-v1_1-xl
        with_concat: true
        with_emb: true
        with_crossattn: true
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    wrap: false
    num_workers: 32
    # num_workers: 1
    train:
      target: ldm.data.laion.LaionSuperRes
      params:
        name: laion/laion2B-en-aesthetic
        size: 256
        lr_size: 64
        dropout: 0.2
        idx_map_name: idx_map_49914159
        # idx_map_name: idx_map_1.3m
        degradation: bsrgan_light
    validation:
      target: ldm.data.laion.LaionSuperRes
      params:
        name: laion/laion2B-en-aesthetic
        size: 256
        lr_size: 64
        dropout: 0.2
        idx_map_name: idx_map_1.3m
        degradation: bsrgan_light
        num_items: 1024
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        increase_log_steps: false
        max_images: 4
        clamp: true
        log_images_kwargs:
          plot_diffusion_rows: true
          plot_progressive_rows: false
          inpaint: false
  modelcheckpoint:
    params:
      every_n_train_steps: 2000
  trainer:
    benchmark: True
    max_epochs: -1
    strategy: fsdp
    precision: bf16