model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: caption
    image_size: 128
    channels: 3
    cond_stage_trainable: false
    conditioning_key: tybrid
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 128
        in_channels: 3
        out_channels: 3
        model_channels: 256
        attention_resolutions: [16, 8, 4]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 1024
        contexts:
          caption:
            seq_dim: 4096
            pooled_dim: 4096
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenPretrainedTextEmbedder
      params:
        model_name: google/t5-v1_1-xxl
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    wrap: false
    num_workers: 32
    train:
      target: ldm.data.laion.LaionTextToImageTrain
      params:
        size: 128
        name: laion/laion2B-en-aesthetic
        dropout: 0.2
        idx_map_name: idx_map_2862193
    validation:
      target: ldm.data.laion.LaionTextToImageValidation
      params:
        size: 128
        name: laion/laion2B-en-aesthetic
        idx_map_name: idx_map_2862193
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        increase_log_steps: false
        max_images: 8
        clamp: true
        log_images_kwargs:
          plot_diffusion_rows: true
          plot_progressive_rows: false
          inpaint: false
  trainer:
    benchmark: True
    max_epochs: -1
    precision: 16
    strategy: fsdp