model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.012
    beta_schedule: cosine
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    first_stage_key: image
    cond_stage_key: multimodal
    image_size: 128
    channels: 3
    cond_stage_trainable: false
    conditioning_key: tybrid
    monitor: val/loss_simple_ema
    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1]
        f_min: [1]
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 128
        in_channels: 5
        out_channels: 3
        model_channels: 160
        checkpoint: fairscale
        attention_resolutions: [32, 16]
        num_res_blocks: 3
        channel_mult: [1, 2, 4, 6]
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
        contexts:
          vision:
            seq_dim: 1024
            pooled_dim: 1024
          lang:
            seq_dim: 2048
            pooled_dim: 2048
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenPretrainedMultiModalEmbedder
      params:
        vision_model_name: google/vit-large-patch16-224
        lang_model_name: google/t5-v1_1-xl
        image_size: 128
        with_concat: true
        with_emb: true
        with_crossattn: true
        with_mask: true
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    wrap: false
    num_workers: 32
    train:
      target: ldm.data.avid.AvidInpaintSizeAware
      params:
        size: 128
        names: [Limit1]
        min_font_size: 10
        max_font_size: 16
        cond_size: 224
        cond_font_size: 24
        dropout: 0.2
    validation:
      target: ldm.data.avid.AvidInpaintSizeAware
      params:
        size: 128
        names: [Random]
        min_font_size: 10
        max_font_size: 16
        cond_size: 224
        cond_font_size: 24
        num_samples: 1024
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2000
        increase_log_steps: false
        max_images: 8
        clamp: true
        log_images_kwargs:
          plot_diffusion_rows: true
          plot_progressive_rows: false
          inpaint: false
          sample: false
  modelcheckpoint:
    params:
      every_n_train_steps: 2000
  trainer:
    benchmark: True
    max_epochs: -1
    precision: 16
    strategy: fsdp